# Browsersync config
BROWSERSYNC:
  # URL of local development server goes here
  url: "http://local.adfinitas.ninja/"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# Set to true if you want static asset revisioning, helpful for cache busting
REVISIONING: false

# Templating
TEMPLATES:
  watch: "src/templates/**/*"
  entries: "src/templates/*.{htm,html,php}"
  injectPartials:
    removeTags: true
    start: "<!-- partial \"{{path}}\""
    end: "-->"

# Gulp will reference these paths when it copies files
PATHS:
  watch_svg : "src/sprites/*.svg"
  dist_svg  : "src/templates/parts/"
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/**/*"
    - "!src/{sprites,sprites/**/*,images,images/**/*,js,js/**/*,templates,templates/**/*,scss,scss/**/*}"
  # Paths to Sass libraries, which can then be loaded with @import
  #sass:
  #  - "node_modules/foundation-sites/scss"
  #  - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/js/app.js"
  # Paths for the package task to include/exclude in .zip archive
  package:
    - "**/*"
    - "!**/node_modules/**"
    - "!**/packaged/**"
    - "!**/src/**"
    - "!**/codesniffer.ruleset.xml"
    - "!**/composer.json"
    - "!**/composer.lock"
    - "!**/config.yml"
    - "!**/config.default.yml"
    - "!**/gulpfile.babel.js"
    - "!**/package.json"
    - "!**/package-lock.json"
    - "!**/webpack.config.js"
  # Paths for PHP CodeSniffer
  phpcs:
    - "**/*.php"
    - "!wpcs"
    - "!wpcs/**"
